apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-fast
  labels:
    app: pv-fast

spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  hostPath:
    path: /mnt/data