apiVersion: 1

datasources:
  - name: Loki
    type: loki
    url: http://loki:3100
    isDefault: false
    editable: false
    version: 1
    uid: loki
    # access: proxy
    # jsonData:
    #   maxLines: 1000